### PR TITLE
Implement multitenancy support

### LINKED ISSUE #120: Registry-sweeper upgrade for multitenant registry
### 💡 Description

Using opensearch serverless

We now have one single opensearch serverless URL.

Sweeper still takes a single node as argument, AWS infrastructure takes care of running the needed sweepers (one for each node). There will be one task definition per node.

Create new roles read/write access that will be associated to the sweeper's ECS task.

We should not need to signed the HTTP requests to connect to OpenSearch and to do it we should use a AWS SDK (see https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-sdk.html). @sjoshi-jpl has example of using this code.
If we want to run sweeper from a local laptop we would still need the signed URLs to be implemented.

### ⚔️ Parent Epic / Related Tickets

_No response_

### PR DESCRIPTION
**Pull request by alexdunnjpl**
## 🗒️ Summary
Fixes outstanding issues with AOSS support

Wraps all instances of 'registry' and 'registry-refs' with a resolution function which returns an altered string iff env var MULTITENANCY_NODE_ID is set to a non-empty value

## ⚙️ Test Data and/or Report
Initially: Manually tested in the empty-value case.  Tested in DEV MCP against registry-en-delta
Changes have been cherry-picked from #122, and not tested yet - must be tested manually in DEV MCP

## ♻️ Related Issues
fixes #120 
related to #60

### CODE REVIEW

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl what's the priority on getting this tested and merged?

**Comment by jordanpadams** [comment]
@alexdunnjpl let's talk about this at the breakout, but I added this ticket associated with this to the Registry API MVP. I really don't think we can deploy the API without have sweepers up an running (or at least the API will not work for several endpoints)

**Review by nutjob4life — APPROVED** [review]

**Comment by alexdunnjpl** [comment]
@jordanpadams I'll put testing this top-of-list, then

**Comment by alexdunnjpl** [comment]
Testing blocked until EC2-attachable role created in MCP-PROD for use in tests.

@sjoshi-jpl has opened a ticket (could you link it here when you get a minute?) as only SAs have access.

sweepers policy will be temporarily attached to the new role to allow manual testing in EC2, then unattached once it's confirmed that sweepers can function with that policy.

**Comment by alexdunnjpl** [comment]
Tested on MCP prod.  Currently running against MCP indices to allow for immediate API deployment without blockage by ECS sweepers deployment.

**Pull request merged**
